version: "3.10"

services:
  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: password
    ports:
      - 2222:2222

  worker:
    build: .
