name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-conda-store-server:
    name: 'Test conda-store-server'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: conda-store-server
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install .[extra,dev]
          sudo apt install wait-for-it -y
      - name: Black Formatting
        run: |
          black --version
          black conda_store_server --diff
          black --check conda_store_server
      - name: Flake8 Formatting
        run: |
          flake8 --version
          flake8
      - name: Release Check
        run: |
          python -m build --sdist
          twine check dist/*
      - name: Unit Tests
        run: |
          pytest
